version: '3.3'

services: 
  web1:
    image: docker_micro
    container_name: web1
    ports:
      - "1000:8080"
  web2:
    image: docker_micro
    container_name: web2
    ports:
      - "2000:8080"    
  web3:
    image: docker_micro
    container_name: web3
    ports:
      - "3000:8080"
  haproxy:
    build: ./proxy
    container_name: haproxy
    ports:
       - "8080:8080"